from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("signup/consumer/", views.consumer_signup, name="consumer_signup"),
    path("signup/farmer/", views.farmer_signup, name="farmer_signup"),
    path("signup/farmer/create/", views.farmer_signup_create, name="farmer_signup_create"),
    path("signup/farmer/profile/", views.farmer_signup_profile, name="farmer_signup_profile"),
    path("verify-email/<uidb64>/<token>/", views.verify_email, name="verify_email"),
    path("resend-verification/", views.resend_verification, name="resend_verification"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("staff/", views.staff_dashboard, name="staff_dashboard"),
    path("profile/", views.profile, name="profile"),
    path("shop-center/", views.farmer_shop_center, name="farmer_shop_center"),
    path("support/chat/", views.support_chat, name="support_chat"),
    path("support/", views.support_ticket_list, name="support_ticket_list"),
    path("support/new/", views.support_ticket_create, name="support_ticket_create"),
    path("support/<int:pk>/", views.support_ticket_detail, name="support_ticket_detail"),
    path("profile/history/", views.account_history, name="account_history"),
    path("profile/addresses/", views.addresses_list, name="addresses"),
    path("profile/addresses/new/", views.address_create, name="address_create"),
    path("profile/addresses/<int:pk>/edit/", views.address_edit, name="address_edit"),
    path("profile/addresses/<int:pk>/default/", views.address_set_default, name="address_set_default"),
    path("profile/addresses/<int:pk>/delete/", views.address_delete, name="address_delete"),
    path("profile/payments/", views.payment_settings, name="payment_settings"),
    path("profile/export/", views.export_my_data, name="export_my_data"),
    path("profile/deactivate/", views.deactivate_my_account, name="deactivate_my_account"),
    path("favorites/", views.favorites_list, name="favorites"),
    path("news/", views.news_list, name="news_list"),
    path("news/manage/", views.news_manage, name="news_manage"),
    path("news/new/", views.news_create, name="news_create"),
    path("news/<int:pk>/edit/", views.news_update, name="news_update"),
    path("news/<int:pk>/delete/", views.news_delete, name="news_delete"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("reports/", views.reports_list, name="reports"),
    path("reports/<int:pk>/", views.report_detail, name="report_detail"),
    path("private/farmers/<int:profile_id>/document/", views.farmer_document_download, name="farmer_document"),
    path("private/reports/<int:report_id>/evidence/", views.report_evidence_download, name="report_evidence"),
    path("private/report-messages/<int:message_id>/attachment/", views.report_attachment_download, name="report_attachment"),
    path("reports/<int:pk>/resolve/", views.resolve_report, name="resolve_report"),
    path("members/<str:role>/", views.members_list, name="members"),
    path("staff/sellers/<int:user_id>/", views.staff_seller_detail, name="staff_seller_detail"),
    path("staff/sellers/<int:user_id>/edit/", views.staff_seller_edit, name="staff_seller_edit"),
    path("members/<int:user_id>/toggle-active/", views.toggle_member_active, name="toggle_member_active"),
    path("messages/", views.conversations_list, name="conversations"),
    path("messages/start/<int:product_id>/", views.conversation_start, name="conversation_start"),
    path("messages/start-seller/<int:seller_id>/", views.conversation_start_seller, name="conversation_start_seller"),
    path("messages/order/<int:order_id>/start/", views.conversation_start_order, name="conversation_start_order"),
    path("messages/<int:pk>/block/", views.conversation_block, name="conversation_block"),
    path("messages/<int:pk>/report/", views.conversation_report, name="conversation_report"),
    path("messages/<int:pk>/", views.conversation_detail, name="conversation_detail"),
    path("notifications/", views.notifications_list, name="notifications"),
    path("notifications/send/", views.send_notification, name="send_notification"),
    path("notifications/send/<int:user_id>/", views.send_notification, name="send_notification_to"),
    path("notifications/<int:pk>/read/", views.mark_notification_read, name="mark_notification_read"),
    path(
        "farmers/<int:profile_id>/<str:action>/",
        views.farmer_verification,
        name="farmer_verification",
    ),
]
