# Generated by Django 6.0.6 on 2026-06-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=20)),
                ('status', models.CharField(choices=[('created', 'สร้างรายการแล้ว'), ('processing', 'กำลังดำเนินการ'), ('paid', 'ชำระแล้ว'), ('failed', 'ไม่สำเร็จ'), ('refunded', 'คืนเงินแล้ว')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='thb', max_length=10)),
                ('checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'การชำระเงิน',
                'verbose_name_plural': 'การชำระเงิน',
                'ordering': ['-created_at'],
            },
        ),
    ]
