# Generated by Django 6.0.6 on 2026-07-29 19:47

import accounts.models
import accounts.validators
import agri_market.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_coupon_minimum_spend_alter_coupon_value_and_more'),
        ('payments', '0002_stripeevent_payment_refunded_amount_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'ยังไม่ได้เริ่มตั้งค่า'), ('pending', 'รอตรวจสอบข้อมูล'), ('active', 'พร้อมรับเงิน'), ('restricted', 'ถูกจำกัดการใช้งาน')], default='not_started', max_length=20)),
                ('country', models.CharField(default='TH', max_length=2)),
                ('details_submitted', models.BooleanField(default=False)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'บัญชีรับเงินของผู้ขาย',
                'verbose_name_plural': 'บัญชีรับเงินของผู้ขาย',
            },
        ),
        migrations.CreateModel(
            name='SellerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='thb', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'รอคำสั่งซื้อสำเร็จ'), ('ready', 'พร้อมโอนเงิน'), ('processing', 'กำลังโอนเงิน'), ('transferred', 'โอนเงินแล้ว'), ('held', 'ระงับไว้ตรวจสอบ'), ('failed', 'โอนเงินไม่สำเร็จ'), ('reversed', 'ยกเลิกรายการแล้ว')], default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ยอดเงินที่ต้องจ่ายผู้ขาย',
                'verbose_name_plural': 'ยอดเงินที่ต้องจ่ายผู้ขาย',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_attempt_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='refund',
            name='evidence',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='refund-evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size, accounts.validators.validate_private_document]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='payment_refunded_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('amount'))), name='payment_refunded_not_over_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_session_id', ''), _negated=True), fields=('checkout_session_id',), name='unique_nonblank_checkout_session'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_intent_id', ''), _negated=True), fields=('payment_intent_id',), name='unique_nonblank_payment_intent'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'processing'])), fields=('payment',), name='one_active_refund_per_payment'),
        ),
        migrations.AddField(
            model_name='sellerpaymentaccount',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellersettlement',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='sellersettlement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sellerpaymentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_account_id', ''), _negated=True), fields=('stripe_account_id',), name='unique_nonblank_stripe_account'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0)), name='settlement_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('fee_rate__gte', 0), ('fee_rate__lte', 100)), name='settlement_fee_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__gte', 0)), name='settlement_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='settlement_net_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__lte', models.F('gross_amount'))), name='settlement_fee_not_over_gross'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__lte', models.F('gross_amount'))), name='settlement_net_not_over_gross'),
        ),
        migrations.AddConstraint(
            model_name='sellersettlement',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_transfer_id', ''), _negated=True), fields=('stripe_transfer_id',), name='unique_nonblank_stripe_transfer'),
        ),
    ]
