# Generated by Django 6.0.6 on 2026-08-01 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_sellerpaymentaccount_sellersettlement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refund',
            name='one_active_refund_per_payment',
        ),
        migrations.AddField(
            model_name='refund',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='resolution_note',
            field=models.TextField(blank=True, default='', verbose_name='เหตุผลการตัดสิน'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('requested', 'รอดำเนินการ'), ('processing', 'กำลังคืนเงิน'), ('succeeded', 'คืนเงินสำเร็จ'), ('failed', 'คืนเงินไม่สำเร็จ'), ('rejected', 'ไม่อนุมัติคำขอ')], default='requested', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'processing', 'failed'])), fields=('payment',), name='one_active_refund_per_payment'),
        ),
    ]
