# Generated by Django 6.0.6 on 2026-08-19 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_refund_one_active_refund_per_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลลูกค้า Stripe',
                'verbose_name_plural': 'ข้อมูลลูกค้า Stripe',
            },
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('method_type', models.CharField(default='card', max_length=30)),
                ('brand', models.CharField(blank=True, max_length=40)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='payments.customerpaymentprofile')),
            ],
            options={
                'verbose_name': 'บัตรที่บันทึกไว้',
                'verbose_name_plural': 'บัตรที่บันทึกไว้',
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('profile',), name='one_default_payment_method_per_profile')],
            },
        ),
    ]
