# Generated by Django 6.0.6 on 2026-09-06 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_customerpaymentprofile_savedpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettlement',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='จำนวนครั้งที่พยายามโอน'),
        ),
        migrations.AddField(
            model_name='sellersettlement',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ลองโอนอีกครั้งเมื่อ'),
        ),
    ]
