# Generated by Django 6.0.6 on 2026-09-28 17:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_received_confirmed_at'),
        ('payments', '0006_sellersettlement_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'สร้างรายการแล้ว'), ('processing', 'กำลังดำเนินการ'), ('paid', 'ชำระแล้ว'), ('failed', 'ไม่สำเร็จ')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='thb', max_length=10)),
                ('checkout_session_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('checkout_attempt_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('checkout_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(related_name='payment_batches', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
