# Generated by Django 6.0.6 on 2026-07-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification_newspost_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'ข่าวสาร', 'verbose_name_plural': 'ข่าวสาร'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'การแจ้งเตือน', 'verbose_name_plural': 'การแจ้งเตือน'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'รายงานปัญหา', 'verbose_name_plural': 'รายงานปัญหา'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ผู้ใช้', 'verbose_name_plural': 'ผู้ใช้'},
        ),
        migrations.AlterField(
            model_name='community',
            name='address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='community',
            name='district',
            field=models.CharField(blank=True, max_length=120, verbose_name='อำเภอ/เขต'),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=180, unique=True, verbose_name='ชื่อชุมชน/สหกรณ์'),
        ),
        migrations.AlterField(
            model_name='community',
            name='province',
            field=models.CharField(max_length=120, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='ชื่อย่อ URL'),
        ),
        migrations.AlterField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='communitystaffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=120, verbose_name='อำเภอ/เขต'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='audience',
            field=models.CharField(choices=[('all', 'ผู้ใช้ทั้งหมด'), ('consumers', 'ผู้บริโภค'), ('farmers', 'เกษตรกรชุมชน'), ('staff', 'เจ้าหน้าที่ชุมชน')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('quality', 'ปัญหาคุณภาพสินค้า'), ('fraud', 'น่าสงสัยหรือฉ้อโกง'), ('abuse', 'พฤติกรรมไม่เหมาะสม'), ('delivery', 'ปัญหาการจัดส่ง'), ('payment', 'ปัญหาการชำระเงิน'), ('other', 'อื่น ๆ')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'เปิดรายการ'), ('reviewing', 'กำลังตรวจสอบ'), ('resolved', 'จัดการแล้ว'), ('dismissed', 'ยกเลิกรายงาน')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('product', 'สินค้า'), ('seller', 'ผู้ขาย'), ('buyer', 'ผู้ซื้อ'), ('order', 'คำสั่งซื้อ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
