# Generated by Django 6.0.6 on 2026-07-28 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_newspost_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'บัตรประจำตัวประชาชน'), ('farm_registration', 'ทะเบียนเกษตรกร'), ('community_certificate', 'หนังสือรับรองชุมชน'), ('other', 'เอกสารอื่น')], default='farm_registration', max_length=30),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='verification_document',
            field=models.FileField(blank=True, upload_to='farmer-verification/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, upload_to='report-evidence/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_hash', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(max_length=64)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'การพยายามเข้าสู่ระบบ',
                'verbose_name_plural': 'การพยายามเข้าสู่ระบบ',
                'constraints': [models.UniqueConstraint(fields=('identifier_hash', 'ip_hash'), name='unique_login_attempt_source')],
            },
        ),
        migrations.CreateModel(
            name='ReportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='report-messages/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.report')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อความในรายงานปัญหา',
                'verbose_name_plural': 'ข้อความในรายงานปัญหา',
                'ordering': ['created_at'],
            },
        ),
    ]
