# Generated by Django 6.0.6 on 2026-07-28 10:17

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verify_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='verification_document',
            field=models.FileField(blank=True, upload_to='farmer-verification/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, upload_to='report-evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='reportmessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='report-messages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size]),
        ),
    ]
