# Generated by Django 6.0.6 on 2026-07-29 19:47

import accounts.models
import accounts.validators
import agri_market.storage
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_separate_community_staff_portal'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'สร้างข้อมูล'), ('update', 'แก้ไขข้อมูล'), ('approve', 'อนุมัติ'), ('reject', 'ปฏิเสธ'), ('block', 'ระงับ'), ('unblock', 'ปลดระงับ'), ('status', 'เปลี่ยนสถานะ'), ('refund', 'คืนเงิน'), ('download', 'ดาวน์โหลดเอกสาร')], max_length=20)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'บันทึกการตรวจสอบ',
                'verbose_name_plural': 'บันทึกการตรวจสอบ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'รอส่ง'), ('sent', 'ส่งแล้ว'), ('failed', 'ส่งไม่สำเร็จ')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'อีเมลที่ระบบส่ง',
                'verbose_name_plural': 'อีเมลที่ระบบส่ง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='verification_document',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='farmer-verification/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size, accounts.validators.validate_private_document]),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='report-evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size, accounts.validators.validate_private_document]),
        ),
        migrations.AlterField(
            model_name='reportmessage',
            name='attachment',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='report-messages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size, accounts.validators.validate_private_document]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_nonblank_user_email_ci'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.community'),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_id'], name='accounts_au_target__6d660f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='accounts_au_actor_i_e03d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['community', 'created_at'], name='accounts_au_communi_a58bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='accounts_em_status_2b26e5_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['to_email', 'created_at'], name='accounts_em_to_emai_794cfb_idx'),
        ),
    ]
