# Generated by Django 6.0.6 on 2026-08-19 09:52

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_conversation_directmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่น ๆ'), ('unspecified', 'ไม่ระบุ')], default='unspecified', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='บ้าน', max_length=60, verbose_name='ชื่อที่อยู่')),
                ('recipient_name', models.CharField(max_length=180, verbose_name='ชื่อผู้รับ')),
                ('phone', models.CharField(max_length=30, verbose_name='เบอร์โทรศัพท์')),
                ('address_line', models.CharField(max_length=255, verbose_name='บ้านเลขที่ ซอย ถนน')),
                ('subdistrict', models.CharField(max_length=120, verbose_name='ตำบล/แขวง')),
                ('district', models.CharField(max_length=120, verbose_name='อำเภอ/เขต')),
                ('province', models.CharField(max_length=120, verbose_name='จังหวัด')),
                ('postal_code', models.CharField(max_length=5, verbose_name='รหัสไปรษณีย์')),
                ('is_default', models.BooleanField(default=False, verbose_name='ที่อยู่เริ่มต้น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ที่อยู่จัดส่ง',
                'verbose_name_plural': 'ที่อยู่จัดส่ง',
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='accounts_de_user_id_75e2ae_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_delivery_address_per_user')],
            },
        ),
    ]
