# Generated by Django 6.0.6 on 2026-08-19 10:11

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_thai_profile_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_file_size], verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่น ๆ'), ('unspecified', 'ไม่ระบุ')], default='unspecified', max_length=20, verbose_name='เพศ'),
        ),
    ]
