# Generated by Django 6.0.6 on 2026-08-19 10:56

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remaining_thai_profile_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), accounts.models.validate_avatar_size], verbose_name='รูปโปรไฟล์'),
        ),
    ]
