# Generated by Django 6.0.6 on 2026-08-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_avatar_upload_rules'),
        ('catalog', '0009_lower_kg_minimum_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ซื้อ'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มสนทนา'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='catalog.product', verbose_name='สินค้า'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขาย'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดตล่าสุด'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='ข้อความ'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.conversation', verbose_name='บทสนทนา'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่ง'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อ่าน'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่ง'),
        ),
    ]
