# Generated by Django 6.0.6 on 2026-08-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_thai_conversation_labels'),
        ('catalog', '0009_lower_kg_minimum_order_quantity'),
        ('orders', '0006_order_shipping_postal_code_order_shipping_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่บล็อก')),
            ],
            options={
                'verbose_name': 'การบล็อกบทสนทนา',
                'verbose_name_plural': 'การบล็อกบทสนทนา',
            },
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_buyer_seller_product_conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='orders.order', verbose_name='คำสั่งซื้อที่เกี่ยวข้อง'),
        ),
        migrations.AddField(
            model_name='report',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.conversation', verbose_name='บทสนทนาที่ถูกรายงาน'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('product', 'สินค้า'), ('seller', 'ผู้ขาย'), ('buyer', 'ผู้ซื้อ'), ('order', 'คำสั่งซื้อ'), ('conversation', 'บทสนทนา')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', True)), fields=('buyer', 'seller', 'product'), name='unique_general_buyer_seller_product_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('buyer', 'seller', 'product', 'order'), name='unique_order_buyer_seller_product_conversation'),
        ),
        migrations.AddField(
            model_name='chatblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_received', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ถูกบล็อก'),
        ),
        migrations.AddField(
            model_name='chatblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บล็อก'),
        ),
        migrations.AddIndex(
            model_name='chatblock',
            index=models.Index(fields=['blocker', 'blocked'], name='accounts_ch_blocker_6bb05d_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_chat_block'),
        ),
        migrations.AddConstraint(
            model_name='chatblock',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='prevent_self_chat_block'),
        ),
    ]
