# Generated by Django 6.0.6 on 2026-08-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_chatblock_and_more'),
        ('catalog', '0009_lower_kg_minimum_order_quantity'),
        ('orders', '0006_order_shipping_postal_code_order_shipping_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='catalog.product', verbose_name='สินค้า'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', True), ('product__isnull', True)), fields=('buyer', 'seller'), name='unique_general_buyer_seller_shop_conversation'),
        ),
    ]
