# Generated by Django 6.0.6 on 2026-08-29 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_conversation_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('refund', 'งานคืนเงิน/คืนสินค้า'), ('account_security', 'บัญชีและความปลอดภัย'), ('finance_fees', 'การเงิน/ค่าธรรมเนียม'), ('general', 'คำถามทั่วไป')], max_length=30, verbose_name='หัวข้อ')),
                ('subject', models.CharField(max_length=200, verbose_name='เรื่องที่ต้องการสอบถาม')),
                ('status', models.CharField(choices=[('open', 'รอผู้ดูแลตอบ'), ('in_progress', 'กำลังดำเนินการ'), ('resolved', 'แก้ไขแล้ว'), ('closed', 'ปิดคำขอ')], default='open', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เปิดคำขอ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='accounts.community', verbose_name='ชุมชน/สหกรณ์')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_handled', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดูแลที่รับเรื่อง')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขาย')),
            ],
            options={
                'verbose_name': 'คำขอถึงผู้ดูแล',
                'verbose_name_plural': 'คำขอถึงผู้ดูแล',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=3000, verbose_name='ข้อความ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่ง')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่ง')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.supportticket', verbose_name='คำขอ')),
            ],
            options={
                'verbose_name': 'ข้อความถึงผู้ดูแล',
                'verbose_name_plural': 'ข้อความถึงผู้ดูแล',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['seller', 'status', 'updated_at'], name='accounts_su_seller__137f03_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'updated_at'], name='accounts_su_status_65bf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='accounts_su_ticket__205d54_idx'),
        ),
    ]
