# Generated by Django 6.0.6 on 2026-09-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_supportticket_supportmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_read_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ผู้ดูแลอ่านล่าสุด'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_admin_message_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ข้อความล่าสุดจากผู้ดูแล'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_seller_message_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ข้อความล่าสุดจากผู้ขาย'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='seller_read_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ผู้ขายอ่านล่าสุด'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'last_seller_message_at'], name='accounts_su_status_7c7cf2_idx'),
        ),
    ]
