# Generated by Django 6.0.6 on 2026-09-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_supportticket_admin_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='client_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='client_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='directmessage',
            constraint=models.UniqueConstraint(fields=('sender', 'client_id'), name='direct_message_client_id'),
        ),
        migrations.AddConstraint(
            model_name='supportmessage',
            constraint=models.UniqueConstraint(fields=('sender', 'client_id'), name='support_message_client_id'),
        ),
    ]
