# Generated by Django 6.0.6 on 2026-09-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_directmessage_client_id_supportmessage_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='หมดอายุเมื่อ'),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='html_body',
            field=models.TextField(blank=True, verbose_name='เนื้อหาอีเมล HTML'),
        ),
    ]
