# Generated by Django 6.0.6 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_emaildelivery_expires_at_emaildelivery_html_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="is_important",
            field=models.BooleanField(
                default=False,
                help_text="ส่งอีเมลถึงกลุ่มผู้อ่านเมื่อเผยแพร่ข่าวนี้",
                verbose_name="ข่าวสำคัญ (ส่งอีเมล)",
            ),
        ),
        migrations.AddField(
            model_name="newspost",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="แจ้งเตือนเมื่อ",
            ),
        ),
    ]
