# Generated by Django 6.0.6 on 2026-09-23 19:15

import accounts.models
import agri_market.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_storecoverslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='attachment',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='chat-media/%Y/%m/', validators=[accounts.models.validate_chat_media_file], verbose_name='ไฟล์แนบ'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'รูปภาพ'), ('video', 'วิดีโอ')], max_length=10, verbose_name='ประเภทสื่อ'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='body',
            field=models.TextField(blank=True, max_length=2000, verbose_name='ข้อความ'),
        ),
    ]
