# Generated by Django 6.0.6 on 2026-09-25 09:22

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_directmessage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='store_cover',
            field=models.FileField(blank=True, upload_to='store-covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_store_image_size], verbose_name='รูปปกหน้าร้าน'),
        ),
        migrations.AlterField(
            model_name='storecoverslide',
            name='image',
            field=models.FileField(upload_to='store-cover-slides/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_store_image_size], verbose_name='รูปสไลด์หน้าร้าน'),
        ),
    ]
