# Generated by Django 6.0.6 on 2026-09-25 11:47

import accounts.models
import accounts.validators
import agri_market.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_enforce_store_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='store_cover',
            field=models.FileField(blank=True, upload_to='store-covers/%Y/%m/', validators=[accounts.models.validate_store_image_extension, accounts.models.validate_store_image_size], verbose_name='รูปปกหน้าร้าน'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='verification_document',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='farmer-verification/%Y/%m/', validators=[accounts.models.validate_document_extension, accounts.models.validate_file_size, accounts.validators.validate_private_document]),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='report-evidence/%Y/%m/', validators=[accounts.models.validate_document_extension, accounts.models.validate_file_size, accounts.validators.validate_private_document]),
        ),
        migrations.AlterField(
            model_name='reportmessage',
            name='attachment',
            field=models.FileField(blank=True, storage=agri_market.storage.private_storage, upload_to='report-messages/%Y/%m/', validators=[accounts.models.validate_document_extension, accounts.models.validate_file_size, accounts.validators.validate_private_document]),
        ),
        migrations.AlterField(
            model_name='storecoverslide',
            name='image',
            field=models.FileField(upload_to='store-cover-slides/%Y/%m/', validators=[accounts.models.validate_store_image_extension, accounts.models.validate_store_image_size], verbose_name='รูปสไลด์หน้าร้าน'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/%Y/%m/', validators=[accounts.models.validate_avatar_extension, accounts.models.validate_avatar_size], verbose_name='รูปโปรไฟล์'),
        ),
    ]
