# Generated by Django 6.0.6 on 2026-06-18 08:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'หมวดสินค้า',
                'verbose_name_plural': 'หมวดสินค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('unit', models.CharField(choices=[('kg', 'กิโลกรัม'), ('pack', 'แพ็ก'), ('bundle', 'มัด'), ('piece', 'ชิ้น'), ('box', 'กล่อง')], default='kg', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(blank=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'ฉบับร่าง'), ('pending', 'รออนุมัติ'), ('active', 'เปิดขาย'), ('rejected', 'ไม่อนุมัติ'), ('archived', 'หยุดขาย')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.community')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สินค้าเกษตร',
                'verbose_name_plural': 'สินค้าเกษตร',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='catalog_pro_status_f78168_idx'), models.Index(fields=['community', 'status'], name='catalog_pro_communi_fff048_idx')],
            },
        ),
    ]
