# Generated by Django 6.0.6 on 2026-07-07 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'ฉบับร่าง'), ('pending', 'รออนุมัติ'), ('active', 'เปิดขาย'), ('rejected', 'ไม่อนุมัติ'), ('blocked', 'ถูกบล็อก'), ('archived', 'หยุดขาย')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='catalog_pro_user_id_b5474d_idx'), models.Index(fields=['product', 'created_at'], name='catalog_pro_product_3d799b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_product_favorite')],
            },
        ),
        migrations.CreateModel(
            name='SellerFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_favorited_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_sellers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='catalog_sel_user_id_19495e_idx'), models.Index(fields=['seller', 'created_at'], name='catalog_sel_seller__80369b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'seller'), name='unique_seller_favorite'), models.CheckConstraint(condition=models.Q(('user', models.F('seller')), _negated=True), name='prevent_self_seller_favorite')],
            },
        ),
    ]
