# Generated by Django 6.0.6 on 2026-07-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_status_productfavorite_sellerfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfavorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'รายการสินค้าที่ถูกใจ', 'verbose_name_plural': 'รายการสินค้าที่ถูกใจ'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'รีวิวสินค้า', 'verbose_name_plural': 'รีวิวสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='sellerfavorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'ร้านค้าที่ถูกใจ', 'verbose_name_plural': 'ร้านค้าที่ถูกใจ'},
        ),
    ]
