# Generated by Django 6.0.6 on 2026-09-23 20:21

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productreviewmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/details/%Y/%m/', validators=[catalog.models.validate_image_file, catalog.models.validate_image_size], verbose_name='รูปประกอบรายละเอียดสินค้า')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'รูปประกอบรายละเอียดสินค้า',
                'verbose_name_plural': 'รูปประกอบรายละเอียดสินค้า',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
