# Generated by Django 6.0.6 on 2026-09-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_detail_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='catalog.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สถิติการเปิดดูสินค้า',
                'verbose_name_plural': 'สถิติการเปิดดูสินค้า',
                'indexes': [models.Index(fields=['seller', 'created_at'], name='catalog_pro_seller__b08693_idx'), models.Index(fields=['product', 'created_at'], name='catalog_pro_product_42d28f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerStoreVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('visited_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สถิติผู้เยี่ยมชมร้าน',
                'verbose_name_plural': 'สถิติผู้เยี่ยมชมร้าน',
                'indexes': [models.Index(fields=['seller', 'visited_on'], name='catalog_sel_seller__c667d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('seller', 'session_key', 'visited_on'), name='unique_daily_seller_store_visit')],
            },
        ),
    ]
