# Generated by Django 6.0.6 on 2026-09-27 10:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productclick_sellerstorevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='รหัส GTIN'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))], verbose_name='จำนวนสั่งซื้อสูงสุดต่อคำสั่งซื้อ'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ความสูงพัสดุ (ซม.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ความยาวพัสดุ (ซม.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ความกว้างพัสดุ (ซม.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_days',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(14)], verbose_name='ระยะเวลาเตรียมสินค้า (วัน)'),
        ),
    ]
