# Generated by Django 6.0.6 on 2026-09-28 07:45

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart_image',
            field=models.FileField(blank=True, help_text='อัปโหลดรูปตารางขนาด (ถ้ามี)', upload_to='products/size-charts/%Y/%m/', validators=[catalog.models.validate_image_file, catalog.models.validate_image_size], verbose_name='รูปตารางขนาดสินค้า'),
        ),
        migrations.CreateModel(
            name='ProductSizeChartRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='เช่น S, M, L หรือ 500 กรัม', max_length=60, verbose_name='ขนาด/ตัวเลือก')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='ความยาว (ซม.)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='ความกว้าง (ซม.)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='ความสูง (ซม.)')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='น้ำหนัก (กรัม)')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='หมายเหตุ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ลำดับ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_chart_rows', to='catalog.product')),
            ],
            options={
                'verbose_name': 'แถวตารางขนาดสินค้า',
                'verbose_name_plural': 'ตารางขนาดสินค้า',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
