# Generated by Django 6.0.6 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_size_chart_image_productsizechartrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailimage',
            name='display_size',
            field=models.CharField(choices=[('small', 'เล็ก'), ('standard', 'มาตรฐาน'), ('wide', 'เต็มความกว้าง')], default='standard', max_length=12),
        ),
    ]
