# Generated by Django 6.0.6 on 2026-09-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_detail_image_display_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailimage',
            name='display_size',
            field=models.CharField(choices=[('small', 'เล็ก'), ('standard', 'มาตรฐาน'), ('wide', 'เต็มความกว้าง'), ('full', 'เต็ม')], default='standard', max_length=12),
        ),
    ]
