# Generated by Django 6.0.6 on 2026-09-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_productdetailimage_display_size'),
        ('orders', '0020_order_received_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.orderitem'),
        ),
    ]
