# Generated by Django 6.0.6 on 2026-09-29 10:56

import catalog.models
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_productreview_order_item'),
        ('orders', '0020_order_received_confirmed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productreview',
            name='product_review_rating_between_1_and_5',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0')), catalog.models.validate_half_star_rating]),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', Decimal('0.5')), ('rating__lte', Decimal('5.0'))), name='product_review_rating_between_1_and_5'),
        ),
    ]
