# Generated by Django 6.0.6 on 2026-06-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('confirmed', 'ยืนยันคำสั่งซื้อ'), ('preparing', 'กำลังเตรียมสินค้า'), ('shipped', 'จัดส่งแล้ว'), ('completed', 'สำเร็จ'), ('cancelled', 'ยกเลิก'), ('refunded', 'คืนเงินแล้ว')], default='pending_payment', max_length=32)),
                ('payment_status', models.CharField(choices=[('unpaid', 'ยังไม่ชำระ'), ('processing', 'กำลังชำระ'), ('paid', 'ชำระแล้ว'), ('failed', 'ชำระไม่สำเร็จ'), ('refunded', 'คืนเงินแล้ว')], default='unpaid', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_name', models.CharField(max_length=180)),
                ('shipping_phone', models.CharField(max_length=30)),
                ('shipping_address', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.community')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในคำสั่งซื้อ',
                'verbose_name_plural': 'รายการสินค้าในคำสั่งซื้อ',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'created_at'], name='orders_orde_buyer_i_1adc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'created_at'], name='orders_orde_seller__3e96fc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['community', 'status'], name='orders_orde_communi_31334d_idx'),
        ),
    ]
