# Generated by Django 6.0.6 on 2026-07-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_populate_order_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='รหัสส่วนลด')),
                ('discount_type', models.CharField(choices=[('fixed', 'ลดเป็นจำนวนเงิน'), ('percent', 'ลดเป็นเปอร์เซ็นต์')], default='fixed', max_length=20, verbose_name='รูปแบบส่วนลด')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='มูลค่าส่วนลด')),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดซื้อขั้นต่ำ')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='เริ่มใช้')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='หมดอายุ')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนสิทธิ์สูงสุด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'รหัสส่วนลด',
                'verbose_name_plural': 'รหัสส่วนลด',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='orders.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='orders.order')),
            ],
            options={
                'verbose_name': 'การใช้รหัสส่วนลด',
                'verbose_name_plural': 'การใช้รหัสส่วนลด',
            },
        ),
    ]
