# Generated by Django 6.0.6 on 2026-08-01 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_coupon_minimum_spend_alter_coupon_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='จังหวัดจัดส่ง'),
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, help_text='เว้นว่างเพื่อใช้เป็นอัตราเริ่มต้นสำหรับจังหวัดที่ไม่มีกฎเฉพาะ', max_length=120, unique=True, verbose_name='จังหวัด')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ค่าจัดส่งเริ่มต้น')),
                ('fee_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ค่าจัดส่งต่อกิโลกรัม')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ยอดซื้อขั้นต่ำที่จัดส่งฟรี')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'อัตราค่าจัดส่ง',
                'verbose_name_plural': 'อัตราค่าจัดส่ง',
                'ordering': ['province'],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_fee__gte', 0)), name='shipping_rate_base_fee_nonnegative'), models.CheckConstraint(condition=models.Q(('fee_per_kg__gte', 0)), name='shipping_rate_per_kg_nonnegative')],
            },
        ),
    ]
