# Generated by Django 6.0.6 on 2026-09-06 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_postal_code_order_shipping_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=120)),
                ('carrier_slug', models.CharField(blank=True, max_length=120)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('checkpoints', models.JSONField(blank=True, default=list)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'การติดตามพัสดุ',
                'verbose_name_plural': 'การติดตามพัสดุ',
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.shipment')),
            ],
        ),
    ]
