# Generated by Django 6.0.6 on 2026-09-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shipment_shipmentevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='next_sync_at',
        ),
    ]
