# Generated by Django 6.0.6 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_shipment_attempts_remove_shipment_last_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shipment",
            name="last_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shipment",
            name="next_sync_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
