# Generated by Django 6.0.6 on 2026-09-28 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='เหตุผลที่ขอคืนสินค้า')),
                ('evidence', models.FileField(blank=True, upload_to='return-evidence/%Y/%m/', verbose_name='หลักฐาน')),
                ('status', models.CharField(choices=[('requested', 'รออนุมัติคืนสินค้า'), ('approved', 'รอส่งสินค้ากลับ'), ('shipped', 'กำลังส่งสินค้ากลับ'), ('received', 'ผู้ขายได้รับสินค้าคืนแล้ว'), ('rejected', 'ไม่อนุมัติคืนสินค้า'), ('refunded', 'คืนเงินสำเร็จ')], default='requested', max_length=20)),
                ('rma_number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='เลข RMA')),
                ('return_recipient', models.CharField(blank=True, max_length=180, verbose_name='ชื่อผู้รับคืน')),
                ('return_phone', models.CharField(blank=True, max_length=30, verbose_name='เบอร์โทรผู้รับคืน')),
                ('return_address', models.TextField(blank=True, verbose_name='ที่อยู่ส่งคืน')),
                ('return_province', models.CharField(blank=True, max_length=120, verbose_name='จังหวัด')),
                ('return_postal_code', models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์')),
                ('seller_note', models.TextField(blank=True, verbose_name='ข้อความจากผู้ขาย')),
                ('return_carrier', models.CharField(blank=True, max_length=120, verbose_name='บริษัทขนส่งขากลับ')),
                ('return_tracking_number', models.CharField(blank=True, max_length=120, verbose_name='เลขพัสดุขากลับ')),
                ('tracking_status', models.CharField(default='Pending', max_length=40, verbose_name='สถานะพัสดุขากลับ')),
                ('tracking_checkpoints', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_return_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='orders.order')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'คำขอคืนสินค้า',
                'verbose_name_plural': 'คำขอคืนสินค้า',
                'ordering': ['-created_at'],
            },
        ),
    ]
