# Generated by Django 6.0.6 on 2026-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
